### ISSUE TITLE
Data type uint64 for superblock missleading

### ISSUE THREAD

**Issue by mmoosstt** [Dr-Emann/Dr-Emann.github.io#10]
Thanks for this [site](https://dr-emann.github.io/squashfs/) was perfect to get into this topic. The only thing confuses me is that according to the following [repository](https://github.com/plougher/squashfs-tools/blob/5ae7238a0ae6fc420f55227d052ce9b1c66a9d0f/kernel/kernel-2.4/include/linux/squashfs_fs.h#L236) the squashfs superblock does make use of u64 datatype. long long in c is an int64 datatype.

**Comment by Dr-Emann** [comment]
I think that's actually a mistake in the squashfs-tools repo:

In the current [linux kernel](https://elixir.bootlin.com/linux/v5.16.1/source/fs/squashfs/squashfs_fs.h#L253), the `bytes_used` field is of type `__le64` (which is a [typedef](https://elixir.bootlin.com/linux/latest/source/tools/include/linux/types.h#L61) for __u64). The [kernel squashfs documentation](https://www.kernel.org/doc/Documentation/filesystems/squashfs.txt) says the max squashfs filesystem size is `2^64` (which implies an unsigned 64 bit number, or it would only be `2^63`).

Also, if you haven't seen it yet, there's also [this document](https://dr-emann.github.io/squashfs/squashfs.html), which was written by the people who make [`squashfs-tools-ng`](https://github.com/AgentD/squashfs-tools-ng). It's largely based on my docs, but fills in some of the details I never got around to.

**Comment by mmoosstt** [comment]
thanks for the input, again what learned :-)
